services:
  baikal:
    build: nginx.dockerfile
    container_name: baikal
    restart: unless-stopped
    volumes:
      - ./config:/var/www/baikal/config
      - ./data:/var/www/baikal/Specific
    networks:
      - frontend
      - db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=frontend"

      # Router
      - "traefik.http.routers.baikal.rule=Host(`cal.mydomain.net`)"
      - "traefik.http.routers.baikal.entrypoints=websecure"
      - "traefik.http.routers.baikal.tls=true"
      - "traefik.http.routers.baikal.tls.certresolver=letsencrypt"

      # Service
      - "traefik.http.services.baikal.loadbalancer.server.port=80"

networks:
  frontend:
    external: true
  db:
    external: true